apiVersion: v1
kind: Service
metadata:
  name: ftps
  labels:
    app: ftps
  annotations:
    metallb.universe.tf/allow-shared-ip: shared
spec:
  externalTrafficPolicy: Cluster
  type: LoadBalancer
  loadBalancerIP: 192.168.99.100
  selector:
    app: ftps
  ports:
    - port: 20
      name: connection
    - port: 21
      name: transfer
    - port: 37000
      name: passive

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: ftps
  labels:
    app: ftps
spec:
  selector:
    matchLabels:
      app: ftps
  strategy:
    type: Recreate
  replicas: 1
  template:
    metadata:
      labels:
        app: ftps
    spec:
      containers:
        - name: ftps
          image: ftps:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 20
            - containerPort: 21
            - containerPort: 37000
